### ISSUE TITLE
Add fullscreen toggle to window menu or toolbar

### ISSUE THREAD

**Issue by jfnavin** [GeoscienceAustralia/earthsci#87]
At the moment the fullscreen toggle is only available on the 3D globe view. If full screen mode is activated, and then the 3D globe view is closed, there is no button on the UI to restore the window to non-fullscreen mode.

Ideally, a menu item and/or toolbar item should be available to toggle this behavior when the globe view is not activated.

**Comment by mdehoog** [comment]
Fixed by d8a8ba2e.
Fullscreen globe shell is disposed when it's corresponding part is closed.
